// ═══════════ CAP 04 — EPP ═══════════
const {Paragraph,TextRun,Table,TableRow,TableCell,
  AlignmentType,BorderStyle,WidthType,ShadingType,
  VerticalAlign,PageBreak} = require('docx');

const bb = (c='CCCCCC',sz=1) => ({style:BorderStyle.SINGLE,size:sz,color:c});
const brd = (c='CCCCCC',sz=1) => ({top:bb(c,sz),bottom:bb(c,sz),left:bb(c,sz),right:bb(c,sz)});
const nb = {style:BorderStyle.NONE,size:0,color:'FFFFFF'};
const nob = {top:nb,bottom:nb,left:nb,right:nb};
const tx = (s,o={}) => new TextRun({text:String(s),font:'Arial',size:o.sz||21,
  bold:o.b,italics:o.i,color:o.c||'2D3748'});
const sp = (n=1) => Array.from({length:n},()=>new Paragraph({spacing:{before:20,after:20},children:[tx('')]}));
const bod = (s) => new Paragraph({spacing:{before:50,after:70},alignment:AlignmentType.JUSTIFIED,children:[tx(s,{sz:21})]});
const h1 = s => new Paragraph({spacing:{before:360,after:160},
  border:{bottom:{style:BorderStyle.SINGLE,size:12,color:'C9A84C',space:6}},
  children:[tx(s,{sz:28,b:true,c:'0A1628'})]});
const h2 = s => new Paragraph({spacing:{before:240,after:100},children:[tx(s,{sz:22,b:true,c:'1A7B8A'})]});
const nl = s => new Paragraph({numbering:{reference:'nl',level:0},spacing:{before:40,after:40},
  alignment:AlignmentType.JUSTIFIED,children:[tx(s,{sz:20})]});
const bl = s => new Paragraph({numbering:{reference:'bl',level:0},spacing:{before:40,after:40},
  alignment:AlignmentType.JUSTIFIED,children:[tx(s,{sz:20})]});
const pgBreak = () => new Paragraph({children:[new PageBreak()]});

function secBanner(num, title, sub) {
  return new Table({width:{size:9900,type:WidthType.DXA},columnWidths:[1500,8400],
    rows:[new TableRow({children:[
      new TableCell({borders:nob,shading:{fill:'C9A84C',type:ShadingType.CLEAR},
        margins:{top:160,bottom:160,left:140,right:140},verticalAlign:VerticalAlign.CENTER,
        children:[new Paragraph({alignment:AlignmentType.CENTER,children:[tx(num,{sz:38,b:true,c:'0A1628'})]})]}),
      new TableCell({borders:nob,shading:{fill:'0A1628',type:ShadingType.CLEAR},
        margins:{top:120,bottom:120,left:220,right:140},children:[
          new Paragraph({spacing:{after:30},children:[tx('C A P Í T U L O',{sz:14,b:true,c:'C9A84C'})]}),
          new Paragraph({spacing:{after:40},children:[tx(title,{sz:24,b:true,c:'FFFFFF'})]}),
          sub?new Paragraph({children:[tx(sub,{sz:15,i:true,c:'C9A84C'})]}):new Paragraph({children:[tx('')]}),
        ]}),
    ]})]});
}
function tbl(headers, rows, widths) {
  const w = widths || headers.map(() => Math.floor(9900/headers.length));
  const headerRow = new TableRow({children: headers.map((h,i) =>
    new TableCell({borders:brd('888888'),shading:{fill:'0A1628',type:ShadingType.CLEAR},
      margins:{top:70,bottom:70,left:100,right:100},width:{size:w[i],type:WidthType.DXA},
      children:[new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:0,after:0},
        children:[tx(h,{sz:16,b:true,c:'C9A84C'})]})]}))});
  const dataRows = rows.map((row,ri) => new TableRow({children: row.map((cell,ci) =>
    new TableCell({borders:brd('CCCCCC'),margins:{top:60,bottom:60,left:100,right:100},
      width:{size:w[ci],type:WidthType.DXA},
      shading:{fill:ri%2===0?'F8F9FA':'FFFFFF',type:ShadingType.CLEAR},
      children:[new Paragraph({spacing:{before:0,after:0},children:[tx(cell,{sz:17})]})]}))
  }));
  return new Table({width:{size:9900,type:WidthType.DXA},columnWidths:w,rows:[headerRow,...dataRows]});
}
function alertBox(title, text, color='C0392B', bgColor='FFF2F0') {
  return new Table({width:{size:9900,type:WidthType.DXA},columnWidths:[9900],
    rows:[new TableRow({children:[new TableCell({
      borders:{top:bb(color,8),bottom:bb(color,8),left:bb(color,8),right:bb(color,8)},
      shading:{fill:bgColor,type:ShadingType.CLEAR},
      margins:{top:100,bottom:100,left:160,right:160},
      children:[
        new Paragraph({spacing:{before:0,after:40},children:[tx(title,{sz:19,b:true,c:color})]}),
        new Paragraph({spacing:{before:0,after:0},alignment:AlignmentType.JUSTIFIED,children:[tx(text,{sz:18,c:'333333'})]})
      ]})]})]});
}
function infoBox(title, text) { return alertBox(title, text, '1A7B8A', 'E8F4F8'); }
function checklist(items) {
  const rows = items.map((item, i) => [String(i+1), item, '\u2610', '\u2610']);
  return tbl(['No.','Item a Verificar','\u2713 OK','\u2717 N/C'], rows, [600,7500,900,900]);
}

const cap04 = [
  pgBreak(),
  secBanner('04','EQUIPO DE PROTECCIÓN PERSONAL (EPP)','Selección, uso, mantenimiento e inspección de todo el EPP de MICSA'),
  ...sp(1),
  h1('4.1 Principio General'),
  bod('El Equipo de Protección Personal es la última línea de defensa contra un accidente — no la primera. El orden correcto de control de riesgos es: Eliminación → Sustitución → Controles de Ingeniería → Controles Administrativos → EPP. Esto significa que el EPP se usa porque los riesgos residuales existen después de aplicar todos los controles anteriores. En las actividades industriales de MICSA, siempre habrá riesgos residuales que el EPP debe cubrir.'),
  bod('El EPP no es opcional. No hay horario donde no aplique. No hay tarea tan pequeña que no requiera el mínimo reglamentario. El supervisor que permita trabajo sin EPP correcto es responsable solidario de cualquier lesión que ocurra.'),
  infoBox('FUNDAMENTO LEGAL: NOM-017-STPS-2008',
    'La norma obliga al patrón a: identificar los riesgos de cada puesto y seleccionar el EPP adecuado, proporcionar el EPP a los trabajadores gratuitamente, capacitar en el uso correcto, verificar que se use, y sustituir el EPP cuando se deteriore. Los trabajadores están obligados a usarlo.'),
  h1('4.2 EPP Básico Obligatorio — Todo el Personal'),
  bod('El siguiente EPP es el mínimo que debe usar todo el personal de MICSA en CUALQUIER frente de trabajo industrial, en todo momento que esté fuera de la zona de oficinas o áreas designadas. No existe excepción por la duración de la tarea o distancia al peligro.'),
  tbl(['EPP','Especificación Técnica','Norma','Vida Útil Máx.','Inspección'],
    [
      ['Casco de Seguridad','Clase E (resistente a electricidad), polietileno de alta densidad. Ala completa preferred. Color según rol: blanco=supervisores, amarillo=general, azul=eléctricos, naranja=visitantes.','ANSI Z89.1 / NOM-115-STPS','5 años desde fabricación, inmediato si hay impacto','Diaria — buscar grietas, abolladuras, decoloración'],
      ['Lentes de Seguridad','ANSI Z87.1 montura wraparound, policarbonato impacto alto. Protección UV400. Antiempañante en espacios confinados. Versión solar para exterior.','ANSI Z87.1','Reemplazar si hay rayones que obstaculicen visión','Antes de cada uso'],
      ['Guantes Multiflex','Nitrilo recubierto, palma y dedos. Mínimo nivel 2 de resistencia a corte (EN388). Evitan cortes con bordes metálicos y abrasión.','EN388 / ANSI 105-2016','3-6 meses según uso','Antes de cada uso — buscar perforaciones'],
      ['Calzado de Seguridad','Bota o zapato punta de acero, suela antiderrapante, protección metatarso. Resistente a aceites e hidrocarburos. Tobillo cubierto mínimo.','NOM-113-STPS / ASTM F2412','Reemplazar cuando suela pierda antiderrapante o puntera dañada','Mensual — estado de suela y puntera'],
      ['Ropa de Trabajo','Pantalón y playera/camisa de manga larga, algodón o material retardante de llama (FR) en trabajos calientes. Sin piezas sueltas que puedan atascarse en maquinaria.','—','Reemplazar cuando esté rota o desgastada','Diaria'],
      ['Chaleco Reflejante','Alta visibilidad clase 2 mínimo. Color amarillo limón o naranja fluorescente. Cintas retro-reflectivas en pecho, espalda y hombros.','ANSI/ISEA 107','Reemplazar cuando reflectivo pierda eficacia','Diaria — visibilidad de reflectores'],
    ],[1400,2800,1500,2100,2100]),
  h1('4.3 EPP Específico por Actividad'),
  h2('4.3.1 Trabajo en Altura (>1.8m)'),
  tbl(['EPP Adicional','Especificación','Norma','Nota Crítica'],
    [
      ['Arnés de cuerpo completo','4 puntos de anclaje (D-ring dorsal, esternal, dos laterales). Tipo paracaídas. Tallas certificadas — no se improvisa. Inspección técnica semestral por empresa certificada.','ANSI Z359.11 / EN361','El D-ring dorsal es el único punto de anclaje para caída libre. Nunca conectar al D-ring lateral para trabajo en suspensión.'],
      ['Eslinga de doble absorción','Longitud máx. 1.8m, absorbedor de impacto (reduce fuerza de choque a 6kN máximo). Sistema Y para 100% tie-off.','ANSI Z359.13','Con absorbedor de impacto desplegado, el sistema queda inutilizable — reemplazar completo.'],
      ['Línea de vida / punto de anclaje','Mínimo 22kN (5,000 lb) de resistencia certificada. Verificada por ingeniero de estructuras si se instala en estructura existente.','ANSI Z359.18','Nunca anclar a tuberías, conductos eléctricos o estructuras no verificadas.'],
      ['Casco con barbuquejo','El mismo casco del EPP básico pero con barbuquejo ajustado al usarse en altura. Sin barbuquejo, el casco cae antes que el trabajador en una caída.','ANSI Z89.1','El barbuquejo es el detalle que más se omite. Es obligatorio en altura.'],
      ['Guantes anticorte nivel 4','Para trabajos con aristas y bordes al instalar componentes en altura.','EN388 A4B4C3','Nivel 4 de corte (ANSI) o nivel D/E (EN388)'],
    ],[2000,3000,1800,3100]),
  h2('4.3.2 Soldadura y Trabajos en Caliente'),
  tbl(['EPP Adicional','Especificación','Norma','Nota Crítica'],
    [
      ['Careta de soldador','Oscurecimiento automático ajustable de DIN 4 a DIN 13. Protección UV/IR. Para soldadura TIG mínimo DIN 10, para arco eléctrico mínimo DIN 11.','ANSI Z87.1 / EN379','La careta manual (sin auto-oscurecimiento) NO está autorizada para soldadura de arco eléctrico porque el trabajador necesita dos manos.'],
      ['Guantes de soldador','Cuero de vaqueta, palma reforzada, puño largo (mínimo 15cm sobre muñeca). Para TIG: guantes más delgados que permiten sensibilidad.','EN12477','Los guantes multiflex del EPP básico NO son guantes de soldador.'],
      ['Delantal de cuero','Cuero de vaqueta, longitud mínima hasta rodillas, ancho completo. Resistente a chispas y salpicaduras de metal fundido.','—','Para soldadura vertical, combinar con escarpines.'],
      ['Escarpines de cuero','Protegen el empeine y el pie de chispas y salpicaduras. Van sobre el calzado de seguridad.','—','—'],
      ['Respirador soldadura','Para soldadura de metales galvanizados, aceros inoxidables o cuando no hay ventilación adecuada. Mínimo N95, preferible respirador con filtros P100+OV.','NIOSH N95 / EN149','La soldadura de metales galvanizados produce vapores de zinc extremadamente peligrosos. Respirador es obligatorio, no opcional.'],
      ['Protección auditiva','Tapones tipo NRR 29 o mayor. Obligatorio en esmerilado y cuando el nivel de ruido supera 85 dB(A).','NOM-011-STPS','El esmerilado supera consistentemente los 100 dB.'],
    ],[2000,3000,1500,3400]),
  h2('4.3.3 Maniobras de Izaje — Riggers y Señaleros'),
  tbl(['EPP Adicional','Especificación','Nota'],
    [
      ['Guantes de rigger','Cuero vaqueta con protección de palma. Permiten sujetar estrobos y eslingas con seguridad.','Los estrobos de acero pueden cortar fácilmente con guantes inadecuados.'],
      ['Chaleco naranja especial','Chaleco de color naranja brillante diferente al estándar del resto de la cuadrilla. Identifica visualmente al señalero desde cualquier ángulo.','Solo la persona con chaleco naranja puede dar señales al operador de grúa.'],
      ['Casco con barbuquejo','El barbuquejo es obligatorio en cualquier zona bajo carga en movimiento.','Una carga que se suelta genera proyectil. El barbuquejo mantiene el casco en su lugar.'],
    ],[2000,4400,3500]),
  h1('4.4 Programa de Inspección de EPP'),
  bod('El EPP deteriorado no protege. La inspección regular es obligatoria para garantizar que el EPP cumple su función protectora. El programa de inspección de MICSA opera en tres niveles:'),
  tbl(['Nivel','Frecuencia','Quién inspecciona','Qué se revisa','Registro'],
    [
      ['Nivel 1 — Diario','Antes de usar','El propio trabajador','Estado visual general: grietas, cortes, deterioro, piezas faltantes. Para arnés: cintas, costuras, hebillas, D-rings.','No requiere registro escrito — parte del ritual diario.'],
      ['Nivel 2 — Mensual','Primer lunes de cada mes','Supervisor de campo (Roberto Ulises Sifuentes Fraire/Hugo Arnoldo de Alba Romero)','Inspección completa de todo el EPP de la cuadrilla. Estado, vigencia, correcto uso. Marca para reposición.','Lista de verificación mensual de EPP firmada por supervisor.'],
      ['Nivel 3 — Semestral','Enero y julio','Fernando + técnico externo certificado','Inspección técnica de arneses, equipos de rescate, detectores de gas, EPP de alto riesgo. Equipo fuera de norma se retira inmediatamente.','Informe técnico con firma del inspector externo.'],
    ],[1300,1300,2000,2800,2500]),
  h1('4.5 Proceso de Entrega y Reposición'),
  bod('Sergio Guzmán administra el inventario de EPP. Cada pieza de EPP entregada a un trabajador queda registrada con firma del receptor en el sistema MICSA OS, vinculada a su número de empleado. La reposición de EPP opera según las siguientes reglas:'),
  nl('EPP deteriorado por uso normal: se repone de inmediato a solicitud del trabajador, sin costo para él.'),
  nl('EPP perdido o dañado por mal uso o negligencia: primera vez se repone con descuento de nómina acordado. Segundo incidente se documenta como falta en el expediente.'),
  nl('EPP después de un impacto o caída (especialmente cascos y arneses): se retira inmediatamente de servicio aunque visualmente parezca sin daño. Los materiales de impacto tienen falla invisible.'),
  nl('Ningún trabajador trabaja sin EPP mientras se tramita la reposición. Si no hay stock, el trabajo se detiene hasta que llegue el reemplazo.'),
];

// ═══════════ CAP 05 — TRABAJOS DE ALTO RIESGO ═══════════
const cap05 = [
  pgBreak(),
  secBanner('05','TRABAJOS DE ALTO RIESGO','Procedimientos detallados para cada actividad crítica de MICSA'),
  ...sp(1),
  h1('5.1 Trabajo en Altura'),
  bod('El trabajo en altura es cualquier trabajo donde exista riesgo de caída de más de 1.8 metros medidos desde el nivel del piso hasta el nivel donde se encuentra el trabajador. En las operaciones de MICSA, el trabajo en altura ocurre durante: instalación de maquinaria en mezanines y plataformas elevadas, maniobras de montaje sobre estructuras, instalación de sistemas de transporte aéreo, trabajos en techos industriales y acceso a partes superiores de equipos de proceso.'),
  bod('Las caídas de altura son la principal causa de muerte en industria a nivel mundial. En México representan el 25% de los accidentes fatales de trabajo. No existe el accidente de caída \'menor\'. Toda caída de más de 1.8 metros es potencialmente mortal.'),
  alertBox('PELIGRO — RIESGO CRÍTICO:',
    'CAÍDA DE ALTURA = RIESGO DE MUERTE. No hay acción que reduzca el tiempo de instalación que valga la vida de un trabajador. El sistema anticaídas se usa siempre, en todo momento que el trabajador está por encima de 1.8 metros. Sin excepción. Sin importar cuánto tiempo dure la tarea.'),
  h2('5.1.1 Jerarquía de Controles para Trabajo en Altura'),
  tbl(['Nivel','Control','Descripción','Aplica cuando'],
    [
      ['1 — Eliminar','Rediseñar la tarea','¿Puede hacerse la tarea desde el suelo? ¿Hay una forma de montar el equipo a nivel de piso primero?','El trabajo puede completarse sin ir a altura.'],
      ['2 — Prevención de caída','Andamiaje con barandal','Plataforma de trabajo con barandal superior (1.05m), intermedio (0.525m) y rodapié (0.1m).','El trabajo dura más de 2 horas en el mismo punto o requiere manipulación de objetos.'],
      ['2 — Prevención de caída','Escalera certificada','Escalera de extensión o tipo tijera, antideslizante, con alguien sosteniéndola abajo. No más de 6 metros.','Acceso temporal a punto de trabajo. No permite trabajar con ambas manos desde la escalera.'],
      ['3 — Restricción de caída','Sistema de restricción','Línea de vida de longitud calculada que impide que el trabajador llegue al borde. No es sistema de detención de caída.','El trabajador puede mantenerse dentro del área segura usando una línea de longitud limitada.'],
      ['4 — Detención de caída','Arnés + eslinga absorbente','Sistema completo de detención: arnés de cuerpo completo + eslinga con absorbedor + punto de anclaje certificado.','Cuando los controles anteriores no son factibles. Siempre como último recurso antes de prohibir el trabajo.'],
    ],[1300,1800,3200,3600]),
  h2('5.1.2 Procedimiento Paso a Paso — Trabajo en Altura'),
  nl('ANTES DEL TRABAJO — Verificación de permiso: Obtener el Permiso de Trabajo en Altura (ver Capítulo 7) firmado por el supervisor y el representante del cliente si aplica.'),
  nl('ANTES DEL TRABAJO — Inspección del área: El supervisor inspecciona el punto de trabajo: superficies, estabilidad, cargas que podrían caer sobre el trabajador, objetos en el camino de caída.'),
  nl('ANTES DEL TRABAJO — Inspección del EPP: Cada trabajador inspecciona su arnés, eslinga y puntos de anclaje físicamente. Si hay duda sobre cualquier componente, no se usa.'),
  nl('ANTES DEL TRABAJO — Identificación del punto de anclaje: El supervisor identifica y verifica la resistencia del punto de anclaje. Mínimo 22 kN (5,000 lb) certificados. Si no está certificado, se instala un punto de anclaje temporal verificado por ingeniería.'),
  nl('ANTES DEL TRABAJO — Cálculo del libre espacio de caída: Se calcula la distancia de caída libre del sistema: longitud de eslinga (máx. 1.8m) + extensión del absorbedor (máx. 1.07m) + altura del trabajador desde el D-ring hasta los pies (~1.5m) + factor de seguridad (0.6m) = mínimo 4.97m de espacio libre bajo el trabajador para que el sistema funcione correctamente.'),
  nl('ANTES DEL TRABAJO — Señalización: Colocar barricada y señalización en el área bajo el trabajo para evitar que personas pasen por la zona de caída potencial.'),
  nl('DURANTE EL TRABAJO — 100% Tie-off: El trabajador debe estar conectado al sistema anticaídas EN TODO MOMENTO que está a más de 1.8m. Antes de desconectar un punto de anclaje, debe estar conectado al siguiente.'),
  nl('DURANTE EL TRABAJO — Sin objetos sueltos: Todas las herramientas van aseguradas con cintas de herramienta o en porta-herramientas. Un martillo que cae desde 3 metros genera la misma energía que un disparo.'),
  nl('DURANTE EL TRABAJO — Comunicación: El supervisor en tierra mantiene comunicación visual o por radio con el trabajador en altura en todo momento.'),
  nl('DURANTE EL TRABAJO — Fatiga: El trabajo en suspensión en arnés no puede durar más de 30 minutos continuos. Síndrome de suspensión puede causar la muerte en pocos minutos. El trabajador baja y descansa antes de volver.'),
  nl('DESPUÉS DEL TRABAJO — Inspección post-uso: Si el arnés fue sometido a una caída o impacto, se retira de servicio aunque visualmente parezca sin daño. Se registra en el sistema y se envía a inspección técnica.'),
  h2('5.1.3 Plan de Rescate en Altura'),
  alertBox('ADVERTENCIA:',
    'ATENCIÓN: Todo trabajo en altura requiere un Plan de Rescate documentado ANTES de que el trabajador suba. Si un trabajador queda suspendido en su arnés, tiene entre 3 y 30 minutos para ser rescatado antes de que el síndrome de suspensión sea mortal. El plan de rescate no puede improvisarse después del accidente.'),
  bod('El Plan de Rescate debe responder estas preguntas ANTES de que el trabajo inicie:'),
  bl('¿Cómo voy a rescatar a un trabajador suspendido desde este punto específico?'),
  bl('¿Tengo el equipo de rescate disponible en el frente de trabajo ahora mismo?'),
  bl('¿Hay al menos una persona capacitada en rescate en el frente de trabajo?'),
  bl('¿A qué número llamo si necesito asistencia médica de emergencia? ¿Cuánto tarda en llegar?'),
  bl('¿Cuál es el acceso para una ambulancia a este frente de trabajo?'),
  h2('5.1.4 Matriz de Riesgos — Trabajo en Altura'),
  tbl(['Actividad','Peligro Identificado','Consecuencia','Probabilidad','Severidad','Nivel de Riesgo'],
    [
      ['Acceso al área de trabajo','Caída de nivel diferente al subir','Lesión grave / muerte','Alta','Crítica','CRÍTICO'],
      ['Instalación en plataforma elevada','Caída libre sin sistema anticaídas','Muerte','Media','Crítica','CRÍTICO'],
      ['Manejo de herramienta en altura','Caída de objeto sobre trabajadores abajo','Lesión grave','Alta','Alta','ALTO'],
      ['Trabajo en borde sin barandal','Desequilibrio y caída','Muerte','Alta','Crítica','CRÍTICO'],
      ['Suspensión en arnés prolongada','Síndrome de suspensión','Muerte','Baja','Crítica','ALTO'],
      ['Anclar en punto no certificado','Falla del anclaje durante caída','Muerte','Media','Crítica','CRÍTICO'],
      ['Usar arnés deteriorado','Falla del arnés durante caída','Muerte','Baja','Crítica','ALTO'],
      ['Subir sin barbuquejo','Casco cae antes que el trabajador','Sin protección craneal','Alta','Alta','ALTO'],
    ],[1600,1600,1500,1400,1200,1600]),
  h2('5.1.5 Checklist Pre-Trabajo en Altura'),
  checklist([
    'El permiso de trabajo en altura está firmado y vigente para esta tarea específica',
    'El arnés de cuerpo completo fue inspeccionado visualmente hoy — sin daños en cintas, costuras ni hebillas',
    'La eslinga con absorbedor de impacto fue inspeccionada — absorbedor sin desplegar, conector sin daño',
    'El punto de anclaje fue verificado con un mínimo de 22 kN de resistencia certificada',
    'El libre espacio de caída fue calculado y es suficiente para el sistema utilizado',
    'El área bajo el trabajo está barricada y señalizada — sin personas transitando',
    'Todas las herramientas y materiales están asegurados con cintas o porta-herramientas',
    'El Plan de Rescate fue revisado — equipo disponible y una persona capacitada presente',
    'La comunicación (visual o radio) entre trabajador en altura y supervisor en tierra está establecida',
    'El trabajador conoce el protocolo de suspensión y la señal para pedir rescate',
    'El barbuquejo del casco está ajustado y abrochado',
    'El supervisor firmó el permiso de trabajo ANTES de que el trabajador suba',
  ]),
  ...sp(1),
  h1('5.2 Maniobras de Izaje'),
  bod('Las maniobras de izaje son la actividad de mayor riesgo en el portafolio de servicios de MICSA. Una maniobra de izaje implica controlar una masa en movimiento en el espacio tridimensional, utilizando equipos mecánicos y la coordinación humana para colocarla con precisión en un punto específico. Las consecuencias de un error en izaje son casi siempre fatales o generan daños catastróficos a la propiedad.'),
  alertBox('PELIGRO — RIESGO CRÍTICO:',
    'REGLA ABSOLUTA DE IZAJE: NUNCA hay personas bajo la carga. Ni por un segundo. Ni el supervisor. Ni el Director. Si la carga cae — y en algún momento durante miles de maniobras hay una falla — cualquier persona bajo ella muere. Esta regla no tiene excepciones ni justificaciones.'),
  h2('5.2.1 Clasificación de Maniobras'),
  tbl(['Categoría','Criterios','Plan de Izaje','Quién Autoriza','Presencia Requerida'],
    [
      ['RUTINARIA','Carga < 1 ton, equipo certificado, trayectoria libre, sin personal ajeno, operación repetitiva ya ejecutada.','AST de izaje','Supervisor de campo','Supervisor + operador + señalero'],
      ['CRÍTICA','Carga 1-10 ton, o espacio limitado, o proximidad a líneas eléctricas, o personal externo en el área, o maniobra no repetitiva.','Plan de Izaje escrito y firmado','Joel (COO)','Joel o supervisor senior + operador certificado + señalero + rigger'],
      ['SUPERCRÍTICA','Carga > 10 ton, o cerca del 75% de la capacidad del equipo, o estructura que requiere izaje doble (dos grúas), o carga con centro de gravedad desconocido, o condiciones de viento.','Plan de Izaje detallado con ingeniería','Jordan + Joel','Jordan o Jordan designado + Joel + supervisor + ingeniero estructural externo si aplica'],
    ],[1400,2400,1800,1600,2700]),
  h2('5.2.2 Elementos del Plan de Izaje'),
  bod('El Plan de Izaje es el documento técnico que describe cómo se va a ejecutar la maniobra de principio a fin. Para maniobras Críticas y Supercríticas es obligatorio tenerlo antes de iniciar.'),
  nl('Descripción completa de la carga: nombre, dimensiones (largo, ancho, alto), peso verificado (no estimado cuando sea posible), ubicación del centro de gravedad, puntos de enganche certificados.'),
  nl('Descripción del equipo de izaje: grúa o montacargas, capacidad nominal, capacidad al radio de trabajo requerido (de la tabla de carga del equipo), porcentaje de la capacidad que representa la carga (máximo 80% para maniobra planeada).'),
  nl('Aparejos de izaje: tipo, diámetro, SWL (Carga de Trabajo Segura) de cada estrobo, eslinga o cadena. El aparejo más débil define la capacidad total del sistema.'),
  nl('Configuración de eslinga: ángulo de eslinga (mientras mayor el ángulo con la vertical, mayor la tensión en cada ramal). A 60° de la vertical, la tensión en cada ramal es el 115% del peso. A 30°, es el 200%.'),
  nl('Secuencia de maniobra: paso a paso desde el enganche hasta el depósito final, con descripción de cada movimiento.'),
  nl('Ruta de la maniobra: trayectoria en planta y en alzado de la carga, zonas restringidas, puntos críticos de la trayectoria.'),
  nl('Cálculo de espacio libre: separación entre carga en movimiento y cualquier obstáculo (mínimo 300mm en todo momento).'),
  nl('Designación del equipo: nombre del operador de grúa, nombre del señalero designado, nombres de los riggers.'),
  nl('Comunicaciones: canal de radio, señales manuales de respaldo, protocolo de emergencia.'),
  nl('Condiciones de cancelación: viento máximo, restricciones de visibilidad, condiciones de suelo.'),
  nl('Plan de contingencia: qué hacer si la carga se traba a mitad de la maniobra, si el equipo falla, si hay interferencia imprevista.'),
  h2('5.2.4 Sistema de Señas Manuales Estándar para Izaje'),
  bod('Las señas manuales son el sistema de comunicación de respaldo cuando el radio falla. TODO el equipo de izaje debe conocerlas. Solo el SEÑALERO DESIGNADO las ejecuta hacia el operador. Si hay confusión en las señas — PARO INMEDIATO hasta aclarar.'),
  tbl(['Movimiento','Seña Manual','Descripción del Gesto'],
    [
      ['IZAR','Brazo extendido horizontalmente, dedo índice apuntando arriba, mover en círculos.','El señalero mueve el dedo en círculos pequeños con el brazo horizontal.'],
      ['BAJAR','Brazo extendido horizontalmente, dedo índice apuntando abajo, mover en círculos.','Igual que izar pero el dedo apunta hacia abajo.'],
      ['PARO','Brazo extendido horizontalmente, palma hacia abajo, mover de lado a lado.','Movimiento horizontal enérgico de la palma. Todos pueden ejecutar esta señal.'],
      ['PARO DE EMERGENCIA','Ambos brazos extendidos horizontalmente, palmas hacia abajo, movimiento rápido.','Señal urgente. CUALQUIER persona puede darla. El operador para INMEDIATAMENTE.'],
      ['DESPACIO','Palma hacia abajo, movimiento lento arriba-abajo.','Se puede combinar con cualquier otra señal para indicar movimiento lento.'],
    ],[1500,3200,5200]),
  h2('5.2.5 Factores de Carga por Ángulo de Eslinga'),
  tbl(['Ángulo con la Vertical','Ángulo entre Ramales','Factor de Carga (FCA)','Nota'],
    [
      ['0° (vertical)','0°','1.00','Carga directa. Sin efecto de ángulo.'],
      ['15°','30°','1.04','Prácticamente sin efecto. Configuración óptima.'],
      ['30°','60°','1.15','Leve incremento de tensión. Aceptable.'],
      ['45°','90°','1.41','Incremento significativo. Verificar SWL.'],
      ['60°','120°','2.00','¡PELIGRO! La tensión en cada ramal es igual al peso total. El aparejo necesita el doble de capacidad.'],
      ['70°','140°','2.92','PROHIBIDO en MICSA sin cálculo de ingeniero.'],
      ['75°','150°','3.86','PROHIBIDO en MICSA.'],
    ],[1800,2000,2200,3900]),
  alertBox('ADVERTENCIA:',
    'REGLA MICSA: El ángulo entre ramales de eslinga NUNCA debe superar los 120° (ángulo con la vertical de 60°) sin verificar que la SWL de los aparejos multiplicada por el FCA sigue siendo mayor al peso de la carga. En caso de duda, usar aparejos de mayor capacidad o añadir un ramal adicional.'),
  h2('5.2.6 Condiciones de Cancelación de Maniobra'),
  bod('Una maniobra de izaje se suspende o cancela inmediatamente ante cualquiera de las siguientes condiciones. La decisión la toma el supervisor o el señalero — no requiere aprobación de nadie:'),
  bl('Viento mayor a 25 km/h para maniobra estándar, o mayor a 15 km/h para cargas de gran área superficial (paneles, estructuras anchas).'),
  bl('Lluvia que reduzca la visibilidad del operador o del señalero sobre la carga.'),
  bl('Persona dentro del perímetro de seguridad establecido.'),
  bl('Falla o comportamiento anormal del equipo de izaje durante la maniobra.'),
  bl('Carga con movimiento pendular que no puede controlarse.'),
  bl('Descubrimiento de peso real diferente al planificado.'),
  bl('Punto de enganche que cede, se deforma o genera sonidos anormales.'),
  bl('Cualquier miembro del equipo que exprese una preocupación de seguridad — SE PARA, SE VERIFICA, SE DECIDE.'),
  ...sp(1),
  h1('5.3 Trabajos en Caliente'),
  bod('Los trabajos en caliente son todas las operaciones que generan chispa, llama, arco eléctrico, calor o radiación capaz de encender materiales combustibles. Incluyen soldadura con electrodo revestido (SMAW), soldadura MIG/MAG, soldadura TIG, corte con arco eléctrico, corte oxigas, plasma, esmerilado y uso de soplete.'),
  infoBox('FUNDAMENTO LEGAL: NOM-027-STPS-2008',
    'Regula las actividades de soldadura y corte en los centros de trabajo. Establece las condiciones de seguridad, el EPP requerido, la ventilación necesaria y el procedimiento de permiso de trabajo caliente.'),
  h2('5.3.1 Procedimiento de Permiso de Trabajo en Caliente'),
  nl('Verificar el área en un radio de 11 metros (35 pies) del punto de trabajo: identificar materiales combustibles o inflamables.'),
  nl('Retirar o proteger todos los materiales combustibles del radio de 11 metros. Si no pueden retirarse, cubrirlos con mantas ignífugas certificadas.'),
  nl('Verificar que no haya líquidos o gases inflamables en tuberías, recipientes o equipos cercanos. Si es posible, solicitar al cliente el aislamiento del sistema.'),
  nl('Tener extintor funcional (mínimo PQS 9 kg) a no más de 5 metros del punto de trabajo, con el pin de seguridad verificado.'),
  nl('Instalar mantas ignífugas o paneles de protección para capturar chispas y salpicaduras. Las chispas de esmerilado viajan hasta 10 metros.'),
  nl('El soldador se pone EPP completo de trabajo en caliente: careta, guantes de vaqueta, delantal, escarpines. Para soldadura de galvanizados o inoxidable: respirador.'),
  nl('Verificar ventilación: el área debe tener ventilación natural o forzada para disipar los humos. Si los humos no se disipan visiblemente, se trabaja con respirador.'),
  nl('Firma del Permiso de Trabajo en Caliente por el supervisor de MICSA y por el representante del cliente en la planta del cliente.'),
  nl('Durante el trabajo: vigilante de incendios designado que NO es el soldador. Esta persona observa el área y está lista para usar el extintor.'),
  nl('Después del trabajo: vigilancia del área durante 30 minutos mínimo después de terminar. Las chispas pueden iniciar incendio varios minutos después de depositarse en material absorbente.'),
  ...sp(1),
  h1('5.4 Trabajo en Espacios Confinados'),
  bod('Un espacio confinado es cualquier espacio que tiene aberturas limitadas de entrada y salida, no está diseñado para ocupación humana continua, y puede contener o tiene potencial para contener una atmósfera peligrosa. En las plantas industriales donde opera MICSA, los espacios confinados más comunes son: tanques de proceso, silos, fosas de bombas, ductos de ventilación, pozos de cables, y cisternas.'),
  alertBox('PELIGRO — RIESGO CRÍTICO:',
    'LOS ESPACIOS CONFINADOS MATAN EN SILENCIO. El gas desplaza el oxígeno sin color ni olor. El trabajador que entra a un espacio sin atmósfera segura pierde la consciencia en segundos. El trabajador que entra a rescatar sin equipo adecuado muere al lado del primero. El 60% de las muertes en espacios confinados son rescatistas. NINGUNA PERSONA ENTRA SIN MEDICIÓN DE GASES Y PERMISO VIGENTE.'),
  h2('5.4.1 Criterios de Atmósfera Segura'),
  tbl(['Parámetro','Valor Seguro para Trabajo','Valor de Peligro Inmediato (IDLH)','Acción si está fuera de rango'],
    [
      ['Oxígeno (O₂)','19.5% — 23.5%','< 16% ó > 25%','Ventilación forzada hasta normalizar. NO ENTRAR hasta rango seguro.'],
      ['Monóxido de Carbono (CO)','< 25 ppm (TWA: 35 ppm)','1,200 ppm','Ventilación. Si persiste: investigar fuente. NO ENTRAR.'],
      ['Sulfuro de Hidrógeno (H₂S)','< 1 ppm (TWA: 1 ppm)','100 ppm','SCBA obligatorio. Evacuar área adyacente.'],
      ['Gas inflamable (LEL)','< 10% del LEL','> 10% del LEL','NO ENTRAR. Ventilación forzada. Investigar fuente.'],
    ],[2000,2200,2400,3300]),
  ...sp(1),
  h1('5.5 Trabajos Eléctricos y LOTO'),
  bod('MICSA ejecuta trabajos electromecánicos que incluyen: instalación de centros de control de motores (CCM), conexión de equipos de producción a la red eléctrica, modificaciones a circuitos de control, y mantenimiento preventivo y correctivo de equipos eléctricos. Estos trabajos presentan los riesgos de electrocución, quemaduras por arco eléctrico y choque eléctrico.'),
  alertBox('PELIGRO — RIESGO CRÍTICO:',
    'LA ENERGÍA ELÉCTRICA NO ES VISIBLE. No hace ruido cuando está presente. No avisa. El voltaje de 480V que usan la mayoría de las plantas industriales es mortal al primer contacto. TODO trabajo eléctrico se hace con energía bloqueada (LOTO) a menos que sea estrictamente necesario el trabajo en caliente, en cuyo caso requiere autorización especial y EPP de arco eléctrico completo.'),
  h2('5.5.1 Procedimiento LOTO (Lock Out / Tag Out)'),
  bod('El LOTO es el procedimiento fundamental de seguridad eléctrica. Garantiza que el equipo no pueda energizarse mientras se trabaja en él. Cada trabajador que trabaja en el equipo coloca SU PROPIO candado. El equipo no se puede energizar hasta que TODOS los candados sean retirados por sus dueños.'),
  checklist([
    'NOTIFICAR: Informar a los trabajadores afectados que el equipo será bloqueado.',
    'IDENTIFICAR: Identificar todas las fuentes de energía del equipo (eléctrica, neumática, hidráulica, mecánica, térmica, gravitacional). Una fuente de energía olvidada puede matar.',
    'APAGAR: Parar el equipo usando los controles normales de paro del operador.',
    'AISLAR: Operar el dispositivo de aislamiento de energía (interruptor, válvula, desconectado) para aislar el equipo de la fuente de energía.',
    'BLOQUEAR: Instalar el candado personal en el dispositivo de aislamiento. Si hay múltiples candados, usar hasp (pasador múltiple). Cada trabajador en el equipo instala SU candado.',
    'ETIQUETAR: Instalar la etiqueta LOTO con el nombre del trabajador, fecha y número de teléfono.',
    'DISIPAR ENERGÍA RESIDUAL: Liberar o bloquear toda la energía almacenada (capacitores, resortes, partes elevadas, presión de fluidos).',
    'VERIFICAR: Antes de tocar el equipo, VERIFICAR la ausencia de energía con el multímetro o con el intento de operación del equipo con el botón de arranque. SI PRENDE — EL LOTO FALLÓ. NO TRABAJAR hasta encontrar qué fuente no fue bloqueada.',
  ]),
  h2('5.5.2 Niveles de Riesgo Eléctrico'),
  tbl(['Voltaje','Riesgo de Contacto','EPP Mínimo Requerido','Trabajo en Caliente'],
    [
      ['< 50V SDCC','Bajo riesgo de electrocución. Riesgo de choque doloroso.','Guantes dieléctricos Cat 00','Solo con permiso supervisor'],
      ['120V-480V (sistemas de control / fuerza)','LETAL. Corriente de 10-50 mA a través del tórax es mortal.','LOTO + Guantes Cat 2 + Careta de arco mínimo 8 cal/cm²','Prohibido sin cálculo de arco y autorización de Joel'],
      ['2,400V-15,000V (media tensión)','EXTREMADAMENTE LETAL. Arco puede ocurrir a distancia.','LOTO + personal especializado externo certificado','PROHIBIDO para personal MICSA sin certificación específica de alta tensión'],
      ['> 15,000V (alta tensión)','INTOCABLE por personal MICSA.','Coordinación con CFE o empresa certificada de alta tensión','PROHIBIDO absolutamente para personal MICSA'],
    ],[1800,2600,2800,2700]),
  ...sp(1),
  h1('5.6 Manejo de Sustancias Químicas Peligrosas'),
  bod('MICSA maneja sustancias químicas peligrosas principalmente como: lubricantes y aceites industriales, solventes de limpieza (thinner, MEK, acetona), gases industriales en cilindros (oxígeno, acetileno, argón, CO₂, nitrógeno), electrodos de soldadura, y los aceites hidráulicos de los equipos de izaje.'),
  infoBox('FUNDAMENTO LEGAL: NOM-018-STPS-2015',
    'El Sistema Armonizado GHS (Sistema Globalmente Armonizado) obliga a etiquetar todas las sustancias peligrosas con los pictogramas de peligro correspondientes y a tener disponible la Hoja de Datos de Seguridad (HDS / SDS) de cada producto.'),
  h2('5.6.1 Manejo de Cilindros de Gas Industrial'),
  tbl(['Gas','Color del Cilindro','Clase de Peligro','Almacenamiento','Uso Seguro'],
    [
      ['Oxígeno (O₂)','Verde / Verde con banda blanca','Oxidante — acelera la combustión','Separado mínimo 6 metros de gases inflamables o separados por barrera de 1.5m de altura.','Nunca lubricar válvulas con aceite. El oxígeno + aceite = explosión.'],
      ['Acetileno (C₂H₂)','Amarillo','Gas inflamable, inestable a > 1.5 bar','Siempre vertical, nunca inclinado más de 30°. La acetona del relleno se derrama y el acetileno se desestabiliza.','Nunca usar a más de 103 kPa (15 PSI). A mayor presión, el acetileno puede explotar espontáneamente.'],
      ['Argón (Ar)','Gris','Gas inerte — asfixiante en espacios confinados','Ventilación adecuada en el área de almacenamiento','En espacios confinados: puede acumularse en zonas bajas y desplazar el oxígeno sin olor ni color.'],
      ['CO₂','Negro','Gas inerte — asfixiante, criogénico líquido','Ventilación adecuada.','No manipular sin guantes criogénicos — el CO₂ líquido genera congelamiento por contacto.'],
      ['Nitrógeno (N₂)','Gris plateado','Gas inerte — asfixiante','Ventilación adecuada.','Ver Argón.'],
    ],[1200,1200,1600,2400,3500]),
];

// ═══════════ CAP 06 — AST ═══════════
const cap06 = [
  pgBreak(),
  secBanner('06','ANÁLISIS DE SEGURIDAD EN EL TRABAJO (AST)','La herramienta diaria de prevención en cada frente de trabajo MICSA'),
  ...sp(1),
  h1('6.1 ¿Qué es el AST?'),
  bod('El Análisis de Seguridad en el Trabajo (AST) es el proceso de identificar los peligros de una tarea específica ANTES de iniciarla y determinar los controles necesarios para ejecutarla con seguridad. Es la herramienta más poderosa de prevención de accidentes que existe en el trabajo de campo porque interrumpe el piloto automático con el que a veces se hacen tareas \'de rutina\' que de rutinarias solo tienen el nombre.'),
  bod('En MICSA, el AST no es un trámite burocrático. Es la conversación de 5-10 minutos que el supervisor tiene con su equipo antes de iniciar CADA tarea de alto riesgo. No es opción hacerlo sentado en la camioneta leyendo un formato de otra empresa. Es participativo: TODOS los que van a ejecutar la tarea participan identificando los peligros. El trabajador que va a ejecutar el trabajo conoce los peligros mejor que el supervisor — porque los enfrenta directamente.'),
  h2('6.1.1 Cuándo se Hace el AST'),
  bl('Al inicio de cada jornada de trabajo para las actividades del día.'),
  bl('Antes de iniciar cualquier tarea nueva que no estaba prevista al inicio del día.'),
  bl('Cuando cambian las condiciones de trabajo (cambio de turno, cambio de área, cambio de condiciones climáticas).'),
  bl('Cuando ocurre un incidente o near-miss, antes de retomar el trabajo.'),
  bl('Siempre en trabajos de alto riesgo: altura, izaje, caliente, espacio confinado, eléctrico.'),
  h1('6.2 Metodología del AST — 4 Pasos'),
  tbl(['Paso','Qué se hace','Cómo se hace','Resultado'],
    [
      ['1 — DIVIDIR LA TAREA','Descomponer la tarea completa en sus pasos individuales secuenciales.','El supervisor lista cada paso en el formato AST. Ejemplo para \'instalar motor eléctrico\': 1) Trasladar motor al área; 2) Izar motor al punto de montaje; 3) Alinear eje; 4) Conectar eléctricamente; 5) Prueba de arranque.','Lista de pasos de la tarea en orden.'],
      ['2 — IDENTIFICAR PELIGROS','Para cada paso, preguntar: ¿qué puede salir mal aquí? ¿qué peligros existen?','Participativo: todos los trabajadores contribuyen. Preguntar por peligros físicos, químicos, ergonómicos, de energía, de entorno.','Lista de peligros por cada paso.'],
      ['3 — EVALUAR EL RIESGO','¿Cuál es la probabilidad de que ocurra el evento peligroso y cuál sería la consecuencia?','Clasificar cada riesgo como: Bajo / Medio / Alto / Crítico. Los riesgos Críticos y Altos requieren controles antes de iniciar.','Priorización de los peligros.'],
      ['4 — DEFINIR CONTROLES','¿Qué vamos a hacer para controlar este peligro?','Para cada peligro: definir la acción de control, quién es responsable de aplicarla y cuándo. Los controles van en la jerarquía: Eliminar → Ingeniería → Administrativo → EPP.','Controles asignados. El equipo los conoce y los aplica.'],
    ],[1500,2200,3400,2800]),
];

// ═══════════ CAP 07 — PERMISOS ═══════════
const cap07 = [
  pgBreak(),
  secBanner('07','PERMISOS DE TRABAJO','Sistema de permisos para actividades de alto riesgo en MICSA'),
  ...sp(1),
  h1('7.1 Sistema de Permisos'),
  bod('Los permisos de trabajo son documentos formales que autorizan la ejecución de trabajos específicos de alto riesgo por un período y en una ubicación definidos, después de verificar que los controles de seguridad están implementados. El permiso cierra el ciclo: autorización → verificación → ejecución → cierre.'),
  tbl(['Tipo de Permiso','Cuándo se requiere','Quién firma por MICSA','Vigencia Máxima'],
    [
      ['Permiso de Trabajo en Altura (PTA)','Cualquier trabajo donde el trabajador esté a más de 1.8m de altura.','Supervisor de campo','1 turno (8 horas). Renovar si se extiende el trabajo.'],
      ['Permiso de Trabajo en Caliente (PTC)','Soldadura, corte, esmerilado, uso de soplete, cualquier fuente de ignición.','Supervisor de campo','4 horas. Renovar con nueva inspección del área.'],
      ['Permiso de Entrada a Espacio Confinado (PEEC)','Cualquier entrada a espacio clasificado como confinado.','Supervisor de campo + representante del cliente si aplica','Duración de la tarea específica. Nueva entrada = nuevo permiso.'],
      ['Permiso de Trabajo Eléctrico (PTE)','Trabajo en instalaciones eléctricas, modificación de circuitos, trabajo en tableros.','Supervisor + Electricista certificado','1 turno. Renovar con nueva verificación de LOTO.'],
      ['Permiso de Izaje Crítico (PIC)','Maniobras categoría Crítica o Supercrítica según 5.2.1.','Joel (COO) + Supervisor de campo','Duración de la maniobra específica. No cubre maniobras adicionales.'],
      ['Permiso de Trabajo con Sustancias Peligrosas (PTSP)','Uso de solventes, gases tóxicos, ácidos, o cualquier sustancia de riesgo elevado.','Supervisor de campo','Duración de la tarea.'],
    ],[2000,2400,2400,3100]),
  h2('7.1.1 Estructura de Todo Permiso de Trabajo'),
  bod('Independientemente del tipo, todo permiso de trabajo de MICSA contiene los siguientes elementos:'),
  nl('Folio único del permiso, tipo de trabajo, fecha y hora de emisión.'),
  nl('Localización exacta del trabajo: planta, nave, zona, número de equipo.'),
  nl('Descripción del trabajo a ejecutar: qué específicamente se va a hacer.'),
  nl('Identificación de todos los trabajadores que ejecutarán el trabajo.'),
  nl('Checklist de verificación de controles aplicados (específico para cada tipo de permiso).'),
  nl('EPP requerido confirmado como disponible y en uso.'),
  nl('Condiciones de cancelación del permiso.'),
  nl('Firma del supervisor de MICSA que verifica y autoriza.'),
  nl('Firma del representante del cliente si el trabajo es en sus instalaciones.'),
  nl('Cierre del permiso al terminar: hora de terminación, condición final del área, firma de cierre.'),
  alertBox('PELIGRO — RIESGO CRÍTICO:',
    'UN PERMISO NO AUTORIZADO ES UN TRABAJO NO AUTORIZADO. Trabajar sin el permiso vigente y firmado es una falta grave que puede generar suspensión inmediata. El permiso existe porque salvó vidas — en MICSA y en todas las industrias donde se implementó.'),
];

// ═══════════ CAP 08 — EMERGENCIAS ═══════════
const cap08 = [
  pgBreak(),
  secBanner('08','PLAN DE EMERGENCIAS','Cómo responde MICSA ante accidentes, lesiones e incidentes graves'),
  ...sp(1),
  h1('8.1 Principio General'),
  bod('Un plan de emergencias que nadie conoce no existe. Por eso este capítulo debe ser estudiado, practicado y recordado por TODO el personal de MICSA. El momento de leer el plan de emergencias no es cuando está ocurriendo la emergencia — es antes. En las primeras horas después de un accidente grave, las acciones correctas o incorrectas determinan si alguien sobrevive.'),
  h1('8.2 Números de Emergencia'),
  tbl(['Servicio','Número','Observaciones'],
    [
      ['Emergencias Generales (SISTEMA 911)','911','Ambulancia, Bomberos, Policía. Dar dirección exacta del frente de trabajo al momento de llamar.'],
      ['Cruz Roja Monclova','866 649 4747 / 644 5353','Hospital más cercano para Ciudad Frontera.'],
      ['IMSS Monclova — Urgencias','866 633 9303','Atención a trabajadores asegurados. Llevar CURP y número de seguridad social.'],
      ['Jordan N. Contreras (Director)','Registrado en MICSA OS','Llamar de inmediato en todo accidente con lesión.'],
      ['Joel Contreras (Operaciones)','Registrado en MICSA OS','Primera llamada ante cualquier incidente en campo.'],
      ['Fernando Contreras (REPSE/RH)','Registrado en MICSA OS','Para accidentes que requieren reporte al IMSS.'],
      ['STPS Coahuila','(844) 410-2301','Para accidentes graves que requieren notificación en 72 horas.'],
    ],[2800,2400,4700]),
  h1('8.3 Protocolo General ante Emergencia'),
  tbl(['Paso','Acción','Responsable','Tiempo Máximo'],
    [
      ['1 — PROTEGER','Garantizar que la emergencia no se extiende. Apagar equipo, cortar energía, evacuar área si hay riesgo de explosión o colapso.','Supervisor de campo o primer respondedor','Inmediato — segundos'],
      ['2 — AVISAR','Activar la alarma o llamar a voz. Que todos en el área sepan que hay emergencia. Llamar al 911 si hay lesionado.','Quien detecta la emergencia','< 1 minuto'],
      ['3 — SOCORRER','Aplicar primeros auxilios básicos al lesionado SIN MOVERLO a menos que esté en peligro inminente. Esperar a los paramédicos para mover si hay sospecha de lesión de columna.','Persona con capacitación en primeros auxilios (mínimo un trabajador por cuadrilla)','Inmediato — mientras llega el 911'],
      ['4 — NOTIFICAR','Llamar a Joel de inmediato. Joel notifica a Jordan. Jordan decide si notifica a la STPS según la gravedad.','Supervisor de campo','< 30 minutos del evento'],
      ['5 — PRESERVAR','No mover ni alterar nada del área del accidente hasta que el supervisor y Fernando hayan documentado la escena. La escena es evidencia.','Supervisor de campo','Tan pronto sea seguro hacerlo'],
    ],[1400,3200,2400,2900]),
  h2('8.3.1 Primeros Auxilios Básicos — Todo el Personal'),
  bod('Al menos UN trabajador por cuadrilla debe tener capacitación y DC-3 vigente en primeros auxilios. Los siguientes principios son el mínimo que TODO el personal de MICSA debe conocer:'),
  nl('Si la persona no responde y no respira normalmente: Llamar al 911 INMEDIATAMENTE. Si sabes RCP: iniciar de inmediato. Si no sabes RCP: el operador del 911 te guiará.'),
  nl('Hemorragia activa: Presión directa sobre la herida con tela limpia o el material disponible. Mantener la presión constante sin quitar la tela. Si una persona se desangra en 3-5 minutos. La presión salva vidas.'),
  nl('Lesión de columna sospechada (accidente de altura, impacto en vehículo, caída): NO MOVER a la persona. Mantener la cabeza inmóvil. Esperar paramédicos.'),
  nl('Quemaduras: Retirar la fuente de calor. Enfriar con agua fría (no helada) durante 10-20 minutos. NO usar hielo, pasta de dientes ni ningún remedio casero. Cubrir con tela limpia húmeda.'),
  nl('Objeto en el ojo: No frotar. No intentar extraerlo. Cubrir el ojo con un escudo limpio (no presionar). Ir a urgencias.'),
  nl('Electrocución: NO tocar a la persona electrizada si sigue en contacto con la fuente. Cortar la corriente primero. Una vez libre de la fuente: RCP si no respira.'),
  nl('Inhalación de gases: Retirar a la persona al aire fresco de inmediato. Si no respira: RCP. Si respira pero está desorientada: posición de recuperación y llamar al 911.'),
  h2('8.3.2 Notificación Obligatoria al IMSS — Aviso de Accidente de Trabajo'),
  bod('Cuando un trabajador de MICSA sufre un accidente de trabajo, Fernando debe presentar el Aviso de Accidente de Trabajo (ST-7) ante el IMSS dentro de las 72 horas siguientes al accidente. Este trámite activa los beneficios del trabajador (atención médica del IMSS, pago de incapacidad, rehabilitación).'),
  alertBox('ADVERTENCIA:',
    'NO reportar un accidente de trabajo al IMSS dentro de las 72 horas es una multa para la empresa. Además, priva al trabajador de sus derechos de seguridad social. Fernando es responsable de este trámite en todo accidente con lesión que requiera atención médica.'),
];

// ═══════════ CAP 09 — REPORTE E INVESTIGACIÓN ═══════════
const cap09 = [
  pgBreak(),
  secBanner('09','REPORTE E INVESTIGACIÓN DE INCIDENTES','Documentación, análisis de causas y acciones correctivas'),
  ...sp(1),
  h1('9.1 Definiciones y Clasificación'),
  bod('Todo evento no planeado que interrumpe o tiene el potencial de interrumpir la normal ejecución de un trabajo se clasifica y se investiga en MICSA. La clasificación determina la profundidad de la investigación y los plazos:'),
  tbl(['Clasificación','Definición','Investigación','Plazo','Reporta a'],
    [
      ['Near-Miss (Cuasi-accidente)','Evento que no generó lesión ni daño pero que bajo condiciones ligeramente diferentes lo habría hecho. Ej: carga que oscila y casi golpea a trabajador.','AST de corrección + nota en F-01','48 horas','Supervisor → Joel → (notificar a Jordan si es grave)'],
      ['Incidente sin lesión','Evento que generó daño a equipo, propiedad o material pero sin lesión a personas.','Informe de incidente completo','72 horas','Supervisor → Joel → Fernando → Jordan'],
      ['Accidente con lesión leve','Lesión que requiere primeros auxilios básicos en campo. El trabajador puede continuar laborando.','Informe completo + análisis de causa raíz','72 horas','Supervisor → Joel → Fernando → Jordan → IMSS si aplica'],
      ['Accidente con incapacidad','Lesión que genera que el trabajador no pueda trabajar al día siguiente. Incapacidad temporal o permanente.','Investigación formal completa con árbol de causas','24 horas del evento','Jordan (responsable) + IMSS obligatorio < 72h + STPS si es grave'],
      ['Accidente mortal','Fallecimiento de cualquier persona como resultado del accidente.','Investigación formal con autoridades','Inmediato','911 + Jordan + IMSS + STPS (obligatorio en < 24h) + Autoridad Laboral'],
    ],[1600,2000,1800,1200,3300]),
  h1('9.2 Investigación de Causas Raíz'),
  bod('La investigación de un accidente o incidente no busca culpables — busca causas. Un trabajador que se lesiona porque no usó el EPP es la causa inmediata. La pregunta correcta es: ¿por qué no usó el EPP? ¿No había EPP disponible? ¿No fue capacitado? ¿El supervisor lo permitía? Esas son las causas raíz — y esas son las que hay que corregir para que no vuelva a ocurrir.'),
  bod('MICSA usa el método de los \'5 Porqués\' para investigar las causas raíz de cada accidente:'),
  tbl(['Pregunta','Ejemplo con Accidente de Caída'],
    [
      ['¿Por qué ocurrió el accidente?','El trabajador cayó de la plataforma.'],
      ['¿Por qué cayó?','No estaba conectado al sistema anticaídas.'],
      ['¿Por qué no estaba conectado?','El punto de anclaje más cercano estaba a 3 metros y el supervisor no lo indicó.'],
      ['¿Por qué el supervisor no lo indicó?','El supervisor no verificó los puntos de anclaje antes de empezar el trabajo.'],
      ['¿Por qué no los verificó?','El supervisor no tiene la capacitación en trabajo en altura correctamente documentada — su DC-3 venció hace 8 meses.'],
      ['CAUSA RAÍZ IDENTIFICADA','Falta de actualización de DC-3 del supervisor en trabajo en altura. Acción correctiva: programa de actualización de DC-3 con alerta automática 60 días antes del vencimiento.'],
    ],[3000,6900]),
  h1('9.3 Cultura de Reporte'),
  bod('En MICSA, reportar un near-miss o un incidente sin lesión NUNCA genera consecuencias negativas para quien reporta. Al contrario — el trabajador que reporta un cuasi-accidente está evitando el accidente real. Es un héroe anónimo del sistema de seguridad.'),
  bod('Jordan tiene el compromiso de agradecer personalmente cada near-miss reportado. El equipo que más near-misses reporta es el equipo más seguro — porque tiene los ojos abiertos. El equipo que nunca reporta nada no es el más seguro — es el que no está viendo o no está reportando.'),
  infoBox('META MICSA 2026',
    '0 accidentes con incapacidad. Mínimo 12 near-misses reportados al año (uno por mes). 100% de incidentes investigados con acción correctiva documentada. Programa de reconocimiento mensual para cuadrilla con mejor reporte de seguridad.'),
];

// ═══════════ CAP 10 — CAPACITACIÓN ═══════════
const cap10 = [
  pgBreak(),
  secBanner('10','PROGRAMA DE CAPACITACIÓN','Formación en seguridad de todo el equipo MICSA'),
  ...sp(1),
  h1('10.1 Principio'),
  bod('Ningún trabajador de MICSA realiza trabajo de alto riesgo sin capacitación verificada y documentada. Un DC-3 vencido equivale a no tener capacitación. La capacitación no es un gasto — es la inversión más barata comparada con el costo de un accidente: días de incapacidad, sustitución del trabajador, daño a equipos, multas, tiempo de investigación, impacto en la moral del equipo y en la reputación de MICSA.'),
  h1('10.2 Matriz de Capacitación por Rol'),
  bod('● = Capacitación obligatoria con DC-3. ○ = Capacitación recomendada sin DC-3 obligatorio.'),
  tbl(['Tema de Capacitación','Jordan','Joel','Fernando','Supervisores','Cuadrilla','Sergio','Alexis','Frec.'],
    [
      ['Inducción General de Seguridad MICSA','○','○','○','○','○','○','○','Ingreso'],
      ['Uso correcto de EPP','○','○','○','●','●','●','○','Anual'],
      ['Trabajo en Altura','○','●','●','●','●','○','○','Anual'],
      ['Maniobras de Izaje — Rigger','○','●','●','●','●','○','○','2 años'],
      ['Señalero de Grúa','○','○','○','●','●','○','○','2 años'],
      ['Soldadura y Trabajos en Caliente','○','○','○','●','●','○','○','Anual'],
      ['Espacios Confinados','○','●','●','●','●','○','○','Anual'],
      ['LOTO — Control de Energía','○','●','●','●','●','●','○','Anual'],
      ['Primeros Auxilios','●','●','●','●','●','●','○','2 años'],
      ['Uso de Extintor','●','●','●','●','●','●','●','Anual'],
      ['Investigación de Accidentes','●','●','●','●','○','○','○','Anual'],
      ['NOM-035 — Factores Psicosociales','●','●','●','●','●','●','●','Anual'],
      ['Manejo de Sustancias Peligrosas','○','●','●','●','●','●','○','Anual'],
      ['Protección contra Arco Eléctrico','○','●','●','●','●','○','○','Anual'],
    ],[2200,700,700,900,1200,1000,800,800,800]),
  h1('10.3 Calendario Anual de Capacitación'),
  tbl(['Mes','Tema Principal','Duración','Instructor','Participantes'],
    [
      ['Enero','Inducción anual de seguridad MICSA + revisión de este documento','4 horas','Fernando','Todo el personal'],
      ['Febrero','Trabajo en altura — teórico y práctico con arneses','8 horas','Externo certificado','Supervisores + cuadrilla'],
      ['Marzo','Maniobras de izaje — teoría ASME B30 + práctica en campo','8 horas','Externo certificado','Supervisores + riggers'],
      ['Abril','LOTO — Control de energías peligrosas','4 horas','Fernando + electricista externo','Todo el personal campo'],
      ['Mayo','Trabajos en caliente + soldadura segura','4 horas','Fernando','Supervisores + soldadores'],
      ['Junio','Primeros auxilios + RCP + uso de DEA','8 horas','Cruz Roja o paramédico certificado','Todo el personal'],
      ['Julio','Espacios confinados — teoría + simulacro','8 horas','Externo certificado','Supervisores + cuadrilla'],
      ['Agosto','Uso de extintor — práctico con fuego real','2 horas','Bomberos o externo','Todo el personal'],
      ['Septiembre','Manejo de sustancias peligrosas + GHS','4 horas','Fernando','Todo el personal'],
      ['Octubre','Protección contra arco eléctrico + NFPA 70E','4 horas','Externo certificado','Supervisores + electricistas'],
      ['Noviembre','NOM-035 — Factores psicosociales','4 horas','Psicólogo externo','Todo el personal'],
      ['Diciembre','Revisión de incidentes del año + lecciones aprendidas','2 horas','Jordan + Joel + Fernando','Todo el personal'],
    ],[1200,2800,1000,2200,2700]),
];

// ═══════════ CAP 11 — INSPECCIONES ═══════════
const cap11 = [
  pgBreak(),
  secBanner('11','INSPECCIONES Y AUDITORÍAS','Sistema de verificación del cumplimiento de seguridad en campo y administrativo'),
  ...sp(1),
  h1('11.1 Sistema de Inspecciones'),
  tbl(['Tipo','Frecuencia','Quién inspecciona','Qué se verifica','Reporte'],
    [
      ['Inspección diaria de campo','Diaria (inicio de jornada)','Supervisor de campo','EPP del equipo, estado del área, AST firmado, permisos vigentes.','Registrado en F-01'],
      ['Inspección semanal de herramienta','Semanal (lunes)','Sergio Guzmán','Estado de toda la herramienta y equipo de izaje en almacén o en campo.','Lista de herramienta en MICSA OS'],
      ['Inspección mensual de EPP','Mensual (1er lunes)','Roberto Ulises Sifuentes Fraire/Hugo Arnoldo de Alba Romero según proyecto','Estado completo del EPP de toda la cuadrilla. Marcar para reposición.','Checklist mensual EPP'],
      ['Auditoría interna de seguridad','Trimestral','Fernando + Joel','Cumplimiento de todos los capítulos de esta política. Documentación, DC-3, permisos, registros.','Informe de auditoría con hallazgos y acciones'],
      ['Auditoría externa / Inspección cliente','Según cliente','Fernando + supervisor','Requisitos específicos del cliente (Carrier, Denso, etc.)','Informe del cliente + plan de acción MICSA'],
      ['Simulacro de emergencia','Semestral (junio y diciembre)','Fernando','Respuesta del equipo ante emergencia simulada. Tiempo de respuesta, uso de extintores, comunicaciones.','Informe de simulacro con mejoras identificadas'],
    ],[1800,1400,2000,2400,2300]),
  h1('11.2 Indicadores de Seguridad (KPI)'),
  bod('MICSA mide el desempeño de su sistema de seguridad con los siguientes indicadores, revisados mensualmente en la Comisión de Seguridad:'),
  tbl(['KPI','Definición','Fórmula','Meta MICSA 2026'],
    [
      ['Tasa de Frecuencia de Accidentes (TF)','Número de accidentes con incapacidad por cada millón de horas trabajadas.','(Núm. accidentes × 1,000,000) / Horas trabajadas','< 2.0'],
      ['Tasa de Gravedad (TG)','Días perdidos por accidentes por cada millón de horas trabajadas.','(Días perdidos × 1,000,000) / Horas trabajadas','< 40'],
      ['Días sin accidente','Conteo de días calendario sin accidente con incapacidad.','Días desde último accidente','360 días'],
      ['% Capacitaciones completadas','Porcentaje del plan anual de capacitación ejecutado.','(Capacitaciones ejecutadas / Planeadas) × 100','100%'],
      ['% DC-3 vigentes','Porcentaje del personal de campo con DC-3 al día.','(Trabajadores con DC-3 vigente / Total campo) × 100','100%'],
      ['Near-misses reportados','Número de cuasi-accidentes reportados voluntariamente.','Conteo mensual','≥ 1 por mes'],
      ['% Permisos correctamente emitidos','Porcentaje de trabajos de alto riesgo con permiso vigente y correcto.','(Trabajos con permiso / Total trabajos AR) × 100','100%'],
    ],[2000,2400,2800,2700]),
];

// ═══════════ CAP 12 — CONDUCTAS PROHIBIDAS ═══════════
const cap12 = [
  pgBreak(),
  secBanner('12','CONDUCTAS PROHIBIDAS Y CONSECUENCIAS','Actos que MICSA no tolera y las consecuencias correspondientes'),
  ...sp(1),
  h1('12.1 Conductas de Riesgo Crítico — Tolerancia Cero'),
  bod('Las siguientes conductas representan un riesgo inmediato para la vida de una o más personas. MICSA aplica política de Tolerancia Cero: la primera vez que se documenta cualquiera de estas conductas, el trabajador es suspendido temporalmente mientras se investiga. La reincidencia puede resultar en terminación de la relación laboral conforme al Art. 47 de la LFT.'),
  tbl(['Conducta Prohibida','Riesgo que Genera','1ª Vez','Reincidencia'],
    [
      ['Trabajar bajo la carga durante maniobra de izaje','Muerte si la carga cae','Suspensión inmediata sin goce de sueldo 3 días + documentación en expediente','Terminación de relación laboral'],
      ['Trabajar en altura sin sistema anticaídas completo (arnés + eslinga + anclaje)','Muerte por caída','Suspensión inmediata 3 días + entrenamiento remedial obligatorio','Terminación de relación laboral'],
      ['Entrar a espacio confinado sin medición de gases y permiso vigente','Muerte por atmósfera peligrosa','Suspensión inmediata 3 días + documentación','Terminación de relación laboral'],
      ['Trabajar bajo influencia de alcohol o drogas','Accidentes que involucran a toda la cuadrilla','Suspensión inmediata + prueba toxicológica + documentación','Terminación de relación laboral'],
      ['Desactivar o manipular indebidamente candados LOTO de otro trabajador','Electrocución del trabajador que puso el candado','Suspensión inmediata 5 días + responsabilidad civil si ocurre accidente','Terminación de relación laboral'],
      ['Sabotear o dañar intencionalmente el EPP propio o de otro trabajador','Lesión del trabajador sin protección','Suspensión inmediata + responsabilidad por daños','Terminación de relación laboral'],
      ['Operar grúa, montacargas o equipo especializado sin certificación vigente','Accidente de izaje o aplastamiento','Suspensión inmediata + proceso de certificación obligatorio antes de operar','Terminación de relación laboral'],
    ],[2200,2200,2800,2700]),
  h2('12.1.1 Conductas de Riesgo Moderado — Progresivas'),
  tbl(['Conducta','1ª Vez','2ª Vez','3ª Vez'],
    [
      ['Trabajar sin parte del EPP básico (sin casco, sin lentes, etc.)','Amonestación verbal documentada + poner EPP de inmediato','Amonestación escrita en expediente','Suspensión sin goce 1 día'],
      ['No firmar el AST antes de iniciar tarea de alto riesgo','Amonestación verbal + se firma antes de continuar','Amonestación escrita','Suspensión sin goce 1 día'],
      ['No reportar un incidente o near-miss','Conversación con supervisor sobre cultura de reporte','Amonestación escrita','Suspensión sin goce 1 día + capacitación remedial'],
      ['Dejar área de trabajo desordenada o sucia con riesgo de tropiezos','Corrección inmediata + amonestación verbal','Amonestación escrita','Suspensión sin goce 1 día'],
      ['Usar herramienta sin EPP específico de la tarea','Corrección inmediata + amonestación verbal','Amonestación escrita','Suspensión sin goce 2 días'],
    ],[2400,2200,2200,3100]),
  bod('El proceso disciplinario cumple en todo momento con los Artículos 47 y 134 de la Ley Federal del Trabajo. Las sanciones se aplican con justicia, sin arbitrariedad y con derecho de audiencia del trabajador. El objetivo no es castigar — es corregir el comportamiento para proteger la vida del trabajador y de sus compañeros.'),
  h1('12.2 Derechos del Trabajador en Materia de Seguridad'),
  bod('La LFT en su artículo 134 fracción II establece que el trabajador tiene derecho a rehusarse a ejecutar un trabajo que ponga en peligro su seguridad o la de sus compañeros. En MICSA, este derecho se ejerce así:'),
  nl('Cualquier trabajador puede decir PARO cuando identifica una condición insegura.'),
  nl('El supervisor investiga la condición de inmediato. No hay represalia por usar el PARO.'),
  nl('Si el supervisor no corrige la condición, el trabajador puede escalar directamente a Joel o a Jordan.'),
  nl('Ningún trabajador puede ser despedido, descontado o sancionado por ejercer su derecho de PARO de seguridad.'),
];

// ═══════════ ANEXOS ═══════════
const anexos = [
  pgBreak(),
  secBanner('AN','ANEXOS — FORMATOS OFICIALES MICSA','Formatos listos para usar en campo y en administración'),
  ...sp(1),
  h1('Anexo A — Permiso de Trabajo en Caliente'),
  tbl(['PERMISO DE TRABAJO EN CALIENTE  |  MICSA-SEG-PTC'],[],[ 9900]),
  bod('Folio: PTC-________  |  Proyecto/Cliente: ______________________________  |  Fecha: ___________  |  Hora inicio: _______  |  Hora fin: _______'),
  bod('Área / Equipo / Nave: ____________________________  |  Tipo de trabajo: ____________________________'),
  bod('Trabajador(es): __________________________________________  |  Supervisor: ____________________________'),
  checklist([
    'Radio de 11 metros verificado y libre de materiales combustibles',
    'Materiales que no pudieron retirarse están cubiertos con manta ignífuga certificada',
    'Extintor PQS ≥9 kg disponible a no más de 5 metros — con carga verificada',
    'Área de trabajo delimitada y señalizada — acceso restringido durante el trabajo',
    'No hay tuberías, recipientes o equipos con líquidos o gases inflamables en el área',
    'Ventilación del área es adecuada — los humos se disipan visiblemente',
    'El soldador tiene EPP completo: careta de oscurecimiento automático, guantes vaqueta, delantal, escarpines',
    'Para galvanizados o inoxidable: respirador P100+OV disponible y en uso',
    'Vigilante de incendios designado — no es el soldador',
    'Se realizó AST específico para esta tarea',
    'Permiso del cliente firmado (si aplica)',
    'Plan de vigilancia post-trabajo de 30 minutos establecido',
  ]),
  ...sp(1),
  bod('Autoriza Supervisor MICSA: Nombre: ___________________ Firma: ___________________'),
  bod('Autoriza Representante Cliente: Nombre: ___________________ Firma: ___________________'),
  ...sp(1),

  h1('Anexo B — Permiso de Trabajo en Altura'),
  tbl(['PERMISO DE TRABAJO EN ALTURA  |  MICSA-SEG-PTA'],[],[9900]),
  bod('Folio: PTA-________  |  Proyecto/Cliente: ______________________________  |  Fecha: ___________  |  Hora inicio: _______  |  Hora fin: _______'),
  bod('Altura máxima de trabajo: ________ m  |  Tipo de trabajo en altura: ______________________________'),
  bod('Trabajadores autorizados: __________________________________________  |  Supervisor: ____________________________'),
  checklist([
    'Arnés de cuerpo completo inspeccionado — sin grietas, cortes ni deterioro en cintas, costuras y herrajes',
    'Eslinga con absorbedor de impacto inspeccionada — absorbedor sin desplegar, conector sin daño',
    'Punto de anclaje verificado — resistencia mínima 22 kN certificada',
    'Libre espacio de caída calculado y verificado como suficiente para el sistema',
    'Barricada del área bajo el trabajo instalada y señalizada',
    'Todas las herramientas aseguradas con cintas o en porta-herramientas',
    'Barbuquejo del casco ajustado y abrochado',
    'Plan de rescate revisado — equipo disponible en frente de trabajo',
    'Al menos un trabajador con capacitación en primeros auxilios presente',
    'Comunicación establecida entre trabajador en altura y supervisor en tierra',
    'AST de trabajo en altura firmado por todos los participantes',
    'Condiciones climáticas verificadas — viento < 25 km/h, sin lluvia ni tormentas',
  ]),
  ...sp(1),

  h1('Anexo C — Permiso de Entrada a Espacio Confinado'),
  tbl(['PERMISO DE ENTRADA A ESPACIO CONFINADO  |  MICSA-SEG-PEEC'],[],[9900]),
  bod('Folio: PEEC-________  |  Proyecto/Cliente: ______________________________  |  Fecha: ___________  |  Hora entrada: _______'),
  bod('Descripción del espacio confinado: ____________________________  |  Peligros conocidos: ____________________________'),
  bod('Trabajador autorizado: __________________________________________  |  Vigilante exterior: ____________________________'),
  bod('Supervisor de entrada: __________________________________________  |  Señal de emergencia establecida: ____________________________'),
  tbl(['Medición Atmosférica','1ª Medición','2ª Medición','3ª Medición','Valor Seguro'],
    [
      ['Oxígeno O₂ (%)','________','________','________','19.5% — 23.5%'],
      ['Monóxido de carbono CO (ppm)','________','________','________','< 25 ppm'],
      ['Sulfuro de hidrógeno H₂S (ppm)','________','________','________','< 1 ppm'],
      ['Gas inflamable LEL (%)','________','________','________','< 10% LEL'],
      ['Hora de medición','________','________','________','Válida 30 min'],
    ],[2200,1700,1700,1700,2600]),
  checklist([
    'Espacio aislado — LOTO completo en todas las fuentes de energía y tuberías. Tapas ciegas instaladas.',
    'Ventilación forzada operando mínimo 20 minutos antes de primera medición',
    'Atmósfera verificada en tres niveles (fondo, medio, superior) — todos dentro de valores seguros',
    'Trabajador tiene detector personal de gases activo y calibrado',
    'Arnés completo con cuerda de rescate conectada al trípode exterior',
    'Iluminación intrínsecamente segura disponible si se requiere',
    'Vigilante exterior en posición — tiene acceso a comunicaciones de emergencia',
    'SCBA disponible en la entrada para rescate si se requiere',
    'Sistema de comunicación entre trabajador interior y vigilante exterior verificado',
    'Plan de rescate específico para este espacio revisado y conocido por todos',
    'Permiso firmado por supervisor MICSA y representante del cliente',
  ]),
  ...sp(1),
  bod('Supervisor de Entrada: Nombre: _______________ Firma: _______________'),
  bod('Vigilante Exterior: Nombre: _______________ Firma: _______________'),
  bod('Trabajador Autorizado: Nombre: _______________ Firma: _______________'),
  ...sp(1),

  h1('Anexo D — Reporte de Incidente'),
  tbl(['REPORTE DE INCIDENTE / ACCIDENTE  |  MICSA-SEG-RI'],[],[9900]),
  bod('Folio: RI-________  |  Fecha del evento: ___________  |  Hora: _______  |  Tipo: ☐ Near-Miss  ☐ Incidente  ☐ Accidente'),
  bod('Proyecto/Cliente: ____________________________  |  Área específica: ____________________________'),
  bod('Persona(s) involucrada(s): __________________________________________  |  Supervisor presente: ____________________________'),
  ...sp(1),
  bod('DESCRIPCIÓN DEL EVENTO:'),
  bod('¿Qué pasó? Describe con detalle, en orden cronológico, qué ocurrió. Incluye qué estaba haciendo el trabajador justo antes del evento.'),
  bod('_____________________________________________________________________________'),
  bod('_____________________________________________________________________________'),
  bod('_____________________________________________________________________________'),
  ...sp(1),
  bod('LESIONES O DAÑOS:'),
  bod('Tipo de lesión: ___________________  |  Parte del cuerpo: ___________________  |  Daño a propiedad: ___________________'),
  bod('Tratamiento inmediato dado: ___________________________________  |  Requirió traslado a médico: ☐ Sí  ☐ No'),
  ...sp(1),
  bod('ANÁLISIS DE CAUSA (5 Porqués):'),
  bod('¿Por qué #1?: _____________________________________________________________________________'),
  bod('¿Por qué #2?: _____________________________________________________________________________'),
  bod('¿Por qué #3?: _____________________________________________________________________________'),
  bod('¿Por qué #4?: _____________________________________________________________________________'),
  bod('¿Por qué #5?: _____________________________________________________________________________'),
  bod('CAUSA RAÍZ IDENTIFICADA: ___________________________________'),
  ...sp(1),
  bod('ACCIONES CORRECTIVAS:'),
  bod('Acción 1: ___________________________  |  Responsable: _______________  |  Fecha límite: ___________'),
  bod('Acción 2: ___________________________  |  Responsable: _______________  |  Fecha límite: ___________'),
  bod('Acción 3: ___________________________  |  Responsable: _______________  |  Fecha límite: ___________'),
  ...sp(2),
  new Table({width:{size:9900,type:WidthType.DXA},columnWidths:[3300,3300,3300],
    rows:[
      new TableRow({children:[
        new TableCell({borders:nob,margins:{top:300,bottom:50,left:100,right:100},
          children:[new Paragraph({alignment:AlignmentType.CENTER,
            border:{bottom:{style:BorderStyle.SINGLE,size:4,color:'333333',space:4}},
            children:[tx('')]})]}),
        new TableCell({borders:nob,margins:{top:300,bottom:50,left:100,right:100},
          children:[new Paragraph({alignment:AlignmentType.CENTER,
            border:{bottom:{style:BorderStyle.SINGLE,size:4,color:'333333',space:4}},
            children:[tx('')]})]}),
        new TableCell({borders:nob,margins:{top:300,bottom:50,left:100,right:100},
          children:[new Paragraph({alignment:AlignmentType.CENTER,
            border:{bottom:{style:BorderStyle.SINGLE,size:4,color:'333333',space:4}},
            children:[tx('')]})]}),
      ]}),
      new TableRow({children:[
        new TableCell({borders:nob,margins:{top:40,bottom:20,left:100,right:100},
          children:[
            new Paragraph({alignment:AlignmentType.CENTER,children:[tx('Reportó (Supervisor)',{sz:18,b:true})]}),
            new Paragraph({alignment:AlignmentType.CENTER,children:[tx('Firma:',{sz:16,c:'888888'})]}),
          ]}),
        new TableCell({borders:nob,margins:{top:40,bottom:20,left:100,right:100},
          children:[
            new Paragraph({alignment:AlignmentType.CENTER,children:[tx('Revisó (Joel / Fernando)',{sz:18,b:true})]}),
            new Paragraph({alignment:AlignmentType.CENTER,children:[tx('Firma:',{sz:16,c:'888888'})]}),
          ]}),
        new TableCell({borders:nob,margins:{top:40,bottom:20,left:100,right:100},
          children:[
            new Paragraph({alignment:AlignmentType.CENTER,children:[tx('Autorizó (Jordan)',{sz:18,b:true})]}),
            new Paragraph({alignment:AlignmentType.CENTER,children:[tx('Firma:',{sz:16,c:'888888'})]}),
          ]}),
      ]}),
    ]}),
];

// ═══════════ LISTA DE PERSONAL ═══════════
const personalMICSA = [
  pgBreak(),
  h1('Plantilla de Personal MICSA'),
  bod('Lista de personal activo de GRUPO MICSA a quienes aplica la presente Política de Seguridad e Higiene Industrial:'),
  tbl(['No.','Nombre Completo'],
    [
      ['1','Jorge Alberto de Alba Reyna'],
      ['2','Reynaldo Rivas García'],
      ['3','Víctor Manuel Bustos Ramos'],
      ['4','Hugo Arnoldo de Alba Romero'],
      ['5','César Ricardo Fabela Rivera'],
      ['6','Arturo Guadalupe Romo de los Santos'],
      ['7','Hugo Edwin de Alba Elizondo'],
      ['8','José Francisco Pérez Martínez'],
      ['9','Manuel Esteban García González'],
      ['10','Joel Roberto González Rivera'],
      ['11','Edgar Pascual Zavala González'],
      ['12','Emmanuel Alejandro Moreno de León'],
      ['13','Roberto Ulises Sifuentes Fraire'],
      ['14','Raúl Juárez Gutiérrez'],
      ['15','Diego Gerardo Ortega Moreno'],
      ['16','Ricardo Rodolfo Meraz Reyes'],
      ['17','Sergio Guzmán'],
      ['18','Víctor Manuel Bustos Ramos'],
      ['19','Sotero Gaona Santiago'],
    ],[1200,8700]),
  bod('Cada uno de los trabajadores listados ha recibido o recibirá copia de esta política, y firma acuse de recibo que se archiva en su expediente personal.'),
];

module.exports = [
  ...cap04,
  ...cap05,
  ...cap06,
  ...cap07,
  ...cap08,
  ...cap09,
  ...cap10,
  ...cap11,
  ...cap12,
  ...anexos,
  ...personalMICSA,
];
